package com.vbs.capsAllocation.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;

@Entity
@Table(name = "time_entries")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TimeEntry {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @ManyToOne
    @JoinColumn(name = "project_id", nullable = false)
    private Project project;

    @Column(nullable = false)
    private LocalDate entryDate;

    @Column(nullable = false)
    private String ldap;

    @ManyToOne
    @JoinColumn(name = "lead_id")
    private User lead;

    @Column(nullable = false)
    private String process;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Activity activity;

    @Column(name = "time_in_mins", nullable = false)
    private Integer timeInMins;

    @Column(name = "attendance_type")
    private String attendanceType;

    @Column(length = 2048)
    private String comment;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TimeEntryStatus status = TimeEntryStatus.PENDING;

    private String rejectionComment;

    @Column(name = "is_overtime")
    private Boolean isOvertime;

    @Column(name = "is_defaulter")
    private Boolean isDefaulter;

    // Auto-generation fields for leave-based time entries
    @Column(name = "is_locked")
    private Boolean isLocked = false;

    @Column(name = "locked_by")
    private String lockedBy;

    @Column(name = "locked_at")
    private LocalDateTime lockedAt;

    @Column(name = "auto_generated")
    private Boolean autoGenerated = false;

    @Column(name = "source_leave_id")
    private Long sourceLeaveId;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        ZonedDateTime istNow = ZonedDateTime.now(ZoneId.of("Asia/Kolkata"));
        createdAt = istNow.toLocalDateTime();
        updatedAt = istNow.toLocalDateTime();
    }

    @PreUpdate
    protected void onUpdate() {
        ZonedDateTime istNow = ZonedDateTime.now(ZoneId.of("Asia/Kolkata"));
        updatedAt = istNow.toLocalDateTime();
    }
}
